eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://project-matheus-microservices:ms-suehtam-eer@localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: 0
spring:
    application:
        name: msclientes
    datasource:
        password: ''
        url: jdbc:h2:mem:msclientes
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: ./logs/log-file.log