eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://project-matheus-microservices:ms-suehtam-eer@${EUREKA_SERVER}:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
    queues:
        emissao-cartoes: emissao-cartoes
server:
    port: 0
spring:
    application:
        name: mscartoes
    profiles:
        active: prod
    datasource:
        password: ''
        url: jdbc:h2:mem:mscartoes
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    rabbitmq:
        host: ${RABBITMQ_SERVER}
        password: guest
        port: 5672
        username: guest
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: ./logs/log-file.log